# Script mode (cmake -P): writes OUTPUT defining PIPEASIO_GIT_COMMIT, the
# source tree's abbreviated commit with "-dirty" for uncommitted changes, or
# "unknown" outside a git checkout.  It runs on every build, so the driver log
# never names the commit of an older build, and it rewrites OUTPUT only when
# the value changes, so nothing recompiles otherwise.
#
#   -DSOURCE_DIR=<source tree> -DOUTPUT=<header> [-DGIT_EXECUTABLE=<git>]
#   [-DCOMMIT=<commit>]
#
# COMMIT, when set, is used instead of asking git.

set(_commit "unknown")
if(COMMIT)
    set(_commit "${COMMIT}")
elseif(GIT_EXECUTABLE)
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" rev-parse --show-toplevel
        OUTPUT_VARIABLE _top OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET RESULT_VARIABLE _rc)
    if(_rc EQUAL 0)
        file(REAL_PATH "${_top}" _top)
        file(REAL_PATH "${SOURCE_DIR}" _src)
    endif()
    # A release tarball unpacked inside another repository, such as an AUR
    # package clone, must not report that repository's commit.
    if(_rc EQUAL 0 AND _top STREQUAL _src)
        execute_process(
            COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}"
                    describe --always --dirty --abbrev=7 --exclude=*
            OUTPUT_VARIABLE _described OUTPUT_STRIP_TRAILING_WHITESPACE
            ERROR_QUIET RESULT_VARIABLE _rc)
        if(_rc EQUAL 0 AND _described)
            set(_commit "${_described}")
        endif()
    endif()
endif()

set(_content "/* Generated by cmake/BuildInfo.cmake. */\n#define PIPEASIO_GIT_COMMIT \"${_commit}\"\n")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" _old)
endif()
if(NOT _old STREQUAL _content)
    file(WRITE "${OUTPUT}" "${_content}")
endif()
